#!/bin/bash

#Check we're in a git directory
if git rev-parse --git-dir > /dev/null 2>&1;
then
    BRANCH_NAME=$(git name-rev HEAD 2> /dev/null | awk "{ print \$2 }")
    if [[ "$BRANCH_NAME" = "master" ]]
    then
        echo "Cannot merge master into itself."
        exit 1
    fi

    # Parse issue number from branch name
    regex=".*/([0-9]+)-.*"
    if [[ $BRANCH_NAME =~ $regex ]]
    then
        BRANCH_NUMBER="${BASH_REMATCH[1]}"
    else
        echo "Unexpected branch name: $BRANCH_NAME. Could not parse issue number."
        exit 1
    fi

    # Merge branch into master and resolve as fixed
    echo "Merging $BRANCH_NAME into master..."
    git checkout master
    git merge --squash $BRANCH_NAME
    git commit -m "Resolves #$BRANCH_NUMBER: Merging $BRANCH_NAME into master"

    # Tag and archive branch
    git checkout $BRANCH_NAME
    git tag archive/$BRANCH_NAME $BRANCH_NAME
    git checkout master
    git branch -D $BRANCH_NAME

else
    echo "Directory is not a git repository."
    exit 1
fi
